Hibernate: create table address (address_id bigint generated by default as identity, city varchar(255), country varchar(255), room_number integer, geo_location_id bigint, primary key (address_id))
Hibernate: create table geo_location (geo_id bigint generated by default as identity, latitude double, longitude double, primary key (geo_id))
Hibernate: create table job (job_id bigint generated by default as identity, salary double, title varchar(255), primary key (job_id))
Hibernate: create table user (user_id bigint generated by default as identity, full_name varchar(255), password varchar(255), user_name varchar(255), job_id bigint, primary key (user_id))
Hibernate: create table user_address (user_user_id bigint not null, user_address_id bigint not null, primary key (user_address_id, user_user_id))
Hibernate: alter table address add constraint FK3n3dkxj2y10hle7vr2ffc8an4 foreign key (geo_location_id) references geo_location
Hibernate: alter table user add constraint FKfftoc2abhot8f2wu6cl9a5iky foreign key (job_id) references job
Hibernate: alter table user_address add constraint FKi317bagyb8rb7fqu3m2j025oo foreign key (user_address_id) references address
Hibernate: alter table user_address add constraint FKcp5ewg2f9dl5bi95u5ebqu265 foreign key (user_user_id) references user
