
insert into job (job_id, title, salary) values (1, 'Director of Sales', 9195);
insert into job (job_id, title, salary) values (2, 'Help Desk Operator', 13298);
insert into job (job_id, title, salary) values (3, 'Database Administrator III', 7141);
insert into job (job_id, title, salary) values (4, 'Staff Accountant III', 15616);
insert into job (job_id, title, salary) values (5, 'VP Product Management', 15312);
insert into job (job_id, title, salary) values (6, 'Mechanical Systems Engineer', 15095);
insert into job (job_id, title, salary) values (7, 'Internal Auditor', 19497);
insert into job (job_id, title, salary) values (8, 'Editor', 12150);
insert into job (job_id, title, salary) values (9, 'Data Coordiator', 10934);
insert into job (job_id, title, salary) values (10, 'VP Quality Control', 6292);
insert into job (job_id, title, salary) values (11, 'Engineer III', 18853);
insert into job (job_id, title, salary) values (12, 'Internal Auditor', 18736);
insert into job (job_id, title, salary) values (13, 'Product Engineer', 7966);
insert into job (job_id, title, salary) values (14, 'Senior Sales Associate', 12491);
insert into job (job_id, title, salary) values (15, 'Data Coordiator', 16257);
insert into job (job_id, title, salary) values (16, 'Clinical Specialist', 3812);
insert into job (job_id, title, salary) values (17, 'Librarian', 5158);
insert into job (job_id, title, salary) values (18, 'Media Manager III', 2959);
insert into job (job_id, title, salary) values (19, 'Research Assistant III', 17202);
insert into job (job_id, title, salary) values (20, 'Programmer II', 7876);
insert into job (job_id, title, salary) values (21, 'Dental Hygienist', 16107);
insert into job (job_id, title, salary) values (22, 'Recruiter', 1741);
insert into job (job_id, title, salary) values (23, 'Senior Sales Associate', 10887);
insert into job (job_id, title, salary) values (24, 'Software Engineer II', 14347);
insert into job (job_id, title, salary) values (25, 'Occupational Therapist', 17990);
insert into job (job_id, title, salary) values (26, 'Assistant Media Planner', 1149);
insert into job (job_id, title, salary) values (27, 'Administrative Officer', 14306);
insert into job (job_id, title, salary) values (28, 'Programmer I', 6282);
insert into job (job_id, title, salary) values (29, 'Junior Executive', 8536);
insert into job (job_id, title, salary) values (30, 'Research Associate', 6000);
insert into job (job_id, title, salary) values (31, 'Nurse Practicioner', 5936);
insert into job (job_id, title, salary) values (32, 'Account Executive', 4084);
insert into job (job_id, title, salary) values (33, 'Analog Circuit Design manager', 9143);
insert into job (job_id, title, salary) values (34, 'Community Outreach Specialist', 11096);
insert into job (job_id, title, salary) values (35, 'Staff Scientist', 14319);
insert into job (job_id, title, salary) values (36, 'VP Accounting', 17705);
insert into job (job_id, title, salary) values (37, 'Account Representative II', 5688);
insert into job (job_id, title, salary) values (38, 'Research Nurse', 8314);
insert into job (job_id, title, salary) values (39, 'Teacher', 13463);
insert into job (job_id, title, salary) values (40, 'Associate Professor', 18588);
