insert into address (address_id, country, city, room_number, geo_location_id) values (1, 'China', 'Zhongjiapu', 1, 32);
insert into address (address_id, country, city, room_number, geo_location_id) values (2, 'China', 'Liancheng', 2, 37);
insert into address (address_id, country, city, room_number, geo_location_id) values (3, 'Canada', 'Labrador City', 3, 20);
insert into address (address_id, country, city, room_number, geo_location_id) values (4, 'Indonesia', 'Merik', 4, 5);
insert into address (address_id, country, city, room_number, geo_location_id) values (5, 'Argentina', 'Albardón', 5, 7);
insert into address (address_id, country, city, room_number, geo_location_id) values (6, 'Guinea', 'Siguiri', 6, 24);
insert into address (address_id, country, city, room_number, geo_location_id) values (7, 'China', 'Meishan', 7, 35);
insert into address (address_id, country, city, room_number, geo_location_id) values (8, 'Nigeria', 'Bida', 8, 8);
insert into address (address_id, country, city, room_number, geo_location_id) values (9, 'Norway', 'Arendal', 9, 7);
insert into address (address_id, country, city, room_number, geo_location_id) values (10, 'Philippines', 'Labnig', 10, 37);
insert into address (address_id, country, city, room_number, geo_location_id) values (11, 'Micronesia', 'Lukunor', 11, 33);
insert into address (address_id, country, city, room_number, geo_location_id) values (12, 'China', 'Yangxipu', 12, 32);
insert into address (address_id, country, city, room_number, geo_location_id) values (13, 'Japan', 'Kamimaruko', 13, 27);
insert into address (address_id, country, city, room_number, geo_location_id) values (14, 'Indonesia', 'Klumpit', 14, 35);
insert into address (address_id, country, city, room_number, geo_location_id) values (15, 'Philippines', 'Cabusao', 15, 13);
insert into address (address_id, country, city, room_number, geo_location_id) values (16, 'Ukraine', 'Berezivka', 16, 27);
insert into address (address_id, country, city, room_number, geo_location_id) values (17, 'Finland', 'Sammatti', 17, 3);
insert into address (address_id, country, city, room_number, geo_location_id) values (18, 'China', 'Qingxi', 18, 19);
insert into address (address_id, country, city, room_number, geo_location_id) values (19, 'Cameroon', 'Garoua Boulaï', 19, 36);
insert into address (address_id, country, city, room_number, geo_location_id) values (20, 'South Korea', 'Tongjin', 20, 39);
insert into address (address_id, country, city, room_number, geo_location_id) values (21, 'Japan', 'Fujinomiya', 21, 7);
insert into address (address_id, country, city, room_number, geo_location_id) values (22, 'Sweden', 'Grängesberg', 22, 24);
insert into address (address_id, country, city, room_number, geo_location_id) values (23, 'China', 'Zumiao', 23, 12);
insert into address (address_id, country, city, room_number, geo_location_id) values (24, 'Indonesia', 'Pumai', 24, 24);
insert into address (address_id, country, city, room_number, geo_location_id) values (25, 'Portugal', 'Montijo', 25, 18);
insert into address (address_id, country, city, room_number, geo_location_id) values (26, 'Russia', 'Shakhty', 26, 26);
insert into address (address_id, country, city, room_number, geo_location_id) values (27, 'Philippines', 'La Carlota', 27, 13);
insert into address (address_id, country, city, room_number, geo_location_id) values (28, 'Kazakhstan', 'Kentau', 28, 18);
insert into address (address_id, country, city, room_number, geo_location_id) values (29, 'Russia', 'Blagodarnyy', 29, 9);
insert into address (address_id, country, city, room_number, geo_location_id) values (30, 'Philippines', 'Tubod', 30, 18);
insert into address (address_id, country, city, room_number, geo_location_id) values (31, 'Uruguay', 'Los Cerrillos', 31, 38);
insert into address (address_id, country, city, room_number, geo_location_id) values (32, 'Belarus', 'Buynichy', 32, 28);
insert into address (address_id, country, city, room_number, geo_location_id) values (33, 'China', 'Xianghua', 33, 21);
insert into address (address_id, country, city, room_number, geo_location_id) values (34, 'Colombia', 'Nariño', 34, 7);
insert into address (address_id, country, city, room_number, geo_location_id) values (35, 'Madagascar', 'Andilamena', 35, 17);
insert into address (address_id, country, city, room_number, geo_location_id) values (36, 'Indonesia', 'Mandala', 36, 24);
insert into address (address_id, country, city, room_number, geo_location_id) values (37, 'Mexico', 'La Palma', 37, 26);
insert into address (address_id, country, city, room_number, geo_location_id) values (38, 'Poland', 'Góra Kalwaria', 38, 26);
insert into address (address_id, country, city, room_number, geo_location_id) values (39, 'Greece', 'Rizómata', 39, 38);
insert into address (address_id, country, city, room_number, geo_location_id) values (40, 'Russia', 'Uchaly', 40, 9);
