CREATE TABLE roles (
   id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
   name VARCHAR(20)
);

CREATE TABLE users (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
   email VARCHAR(50) UNIQUE,
   username VARCHAR(20) UNIQUE,
   password VARCHAR(150),
   account_non_expired BOOLEAN NOT NULL,
   account_non_locked BOOLEAN NOT NULL,
   credentials_non_expired BOOLEAN NOT NULL,
   enabled BOOLEAN NOT NULL
);

CREATE TABLE user_roles (
   role_id INTEGER NOT NULL,
   user_id BIGINT NOT NULL,
   PRIMARY KEY (role_id, user_id),
   FOREIGN KEY (role_id) REFERENCES roles (id),
   FOREIGN KEY (user_id) REFERENCES users (id)
);

