
insert into user (user_id, username, password, full_name, job_id) values (1, 'Philippines', 'Sinuknipan', 1, 34);
insert into user (user_id, username, password, full_name, job_id) values (2, 'Tanzania', 'Mafinga', 2, 25);
insert into user (user_id, username, password, full_name, job_id) values (3, 'China', 'Langkou', 3, 4);
insert into user (user_id, username, password, full_name, job_id) values (4, 'China', 'Penghua', 4, 24);
insert into user (user_id, username, password, full_name, job_id) values (5, 'Mexico', 'Providencia', 5, 36);
insert into user (user_id, username, password, full_name, job_id) values (6, 'Portugal', 'Portel', 6, 38);
insert into user (user_id, username, password, full_name, job_id) values (7, 'Mexico', 'Las Palmas', 7, 19);
insert into user (user_id, username, password, full_name, job_id) values (8, 'China', 'Tiandu', 8, 23);
insert into user (user_id, username, password, full_name, job_id) values (9, 'China', 'Dingtao', 9, 16);
insert into user (user_id, username, password, full_name, job_id) values (10, 'Serbia', 'Gudurica', 10, 24);
insert into user (user_id, username, password, full_name, job_id) values (11, 'Macedonia', 'Чучер - Сандево', 11, 36);
insert into user (user_id, username, password, full_name, job_id) values (12, 'Guadeloupe', 'Jarry', 12, 16);
insert into user (user_id, username, password, full_name, job_id) values (13, 'Indonesia', 'Cemara', 13, 1);
insert into user (user_id, username, password, full_name, job_id) values (14, 'Botswana', 'Mahalapye', 14, 29);
insert into user (user_id, username, password, full_name, job_id) values (15, 'Poland', 'Cisek', 15, 18);
insert into user (user_id, username, password, full_name, job_id) values (16, 'Iceland', 'Vestmannaeyjar', 16, 10);
insert into user (user_id, username, password, full_name, job_id) values (17, 'Indonesia', 'Pantaihambawang', 17, 24);
insert into user (user_id, username, password, full_name, job_id) values (18, 'Indonesia', 'Banjar Medura', 18, 39);
insert into user (user_id, username, password, full_name, job_id) values (19, 'Russia', 'Svetogorsk', 19, 11);
insert into user (user_id, username, password, full_name, job_id) values (20, 'Poland', 'Radostowice', 20, 12);
insert into user (user_id, username, password, full_name, job_id) values (21, 'Syria', 'Khān Shaykhūn', 21, 12);
insert into user (user_id, username, password, full_name, job_id) values (22, 'Brazil', 'São Sebastião do Caí', 22, 8);
insert into user (user_id, username, password, full_name, job_id) values (23, 'China', 'Dejilin', 23, 33);
insert into user (user_id, username, password, full_name, job_id) values (24, 'China', 'Shengmi', 24, 38);
insert into user (user_id, username, password, full_name, job_id) values (25, 'Czech Republic', 'Hrušovany u Brna', 25, 29);
insert into user (user_id, username, password, full_name, job_id) values (26, 'China', 'Hemudu', 26, 18);
insert into user (user_id, username, password, full_name, job_id) values (27, 'Portugal', 'Foros do Trapo', 27, 21);
insert into user (user_id, username, password, full_name, job_id) values (28, 'Lebanon', 'Tripoli', 28, 15);
insert into user (user_id, username, password, full_name, job_id) values (29, 'Canada', 'La Ronge', 29, 17);
insert into user (user_id, username, password, full_name, job_id) values (30, 'Russia', 'Prokhladnyy', 30, 20);
insert into user (user_id, username, password, full_name, job_id) values (31, 'Poland', 'Głuchów', 31, 2);
insert into user (user_id, username, password, full_name, job_id) values (32, 'Cyprus', 'Akaki', 32, 34);
insert into user (user_id, username, password, full_name, job_id) values (33, 'China', 'Yangyong', 33, 13);
insert into user (user_id, username, password, full_name, job_id) values (34, 'China', 'Jiangzao', 34, 26);
insert into user (user_id, username, password, full_name, job_id) values (35, 'Brazil', 'Canguçu', 35, 4);
insert into user (user_id, username, password, full_name, job_id) values (36, 'Honduras', 'La Libertad', 36, 7);
insert into user (user_id, username, password, full_name, job_id) values (37, 'Ukraine', 'Synevyr', 37, 29);
insert into user (user_id, username, password, full_name, job_id) values (38, 'Russia', 'Novovarshavka', 38, 8);
insert into user (user_id, username, password, full_name, job_id) values (39, 'China', 'Sanjiang', 39, 27);
insert into user (user_id, username, password, full_name, job_id) values (40, 'Indonesia', 'Medang', 40, 7);
